CREATE TABLE SportType (Id INT PRIMARY KEY IDENTITY, [Name] VARCHAR(200) NOT NULL);

ALTER TABLE SoccerPitch Add SportTypeId int FOREIGN KEY (SportTypeId) REFERENCES SportType(Id);

ALTER TABLE SoccerPitch ALTER COLUMN SportTypeId INT NOT NULL;